version: '3.3'
services:
    jenkins:
        build:
            context: ./
            args:
                JAVE_OPTS: '-Djenkins.CLI.disabled=true'
        container_name: my_jenkins
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - "jenkins_data:/var/jenkins_home"
            - "./my_marvin.yml:/var/jenkins_conf/my_marvin.yaml"
        environment:
            - CASC_JENKINS_CONFIG=/var/jenkins_conf/my_marvin.yaml
            - USER_CHOCOLATEEN_PASSWORD=password
            - USER_VAUGIE_G_PASSWORD=password
            - USER_I_DONT_KNOW_PASSWORD=password
            - USER_NASSO_PASSWORD=password

volumes:
    jenkins_data: